config/routes.rb
Rails.application.routes.draw do
  resources :teaches
  resources :events
  resources :participates
  resources :competes
  resources :codes
  resources :course_categories
  resources :belong_tos
  resources :groups
  resources :advisors
  resources :log_breaks
  resources :rules
  resources :personal_leaves
  resources :sick_leaves
  resources :leaves
  resources :competitions
  resources :activities
  resources :portfolios
  resources :gpas
  resources :students
  resources :schedules
  resources :time_slots
  resources :enrollments
  resources :sections
  resources :requires
  resources :courses
  resources :curriculums
  resources :departments
  resources :personnels

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'static_pages#index'

  get 'sessions/new'
  post '/signup', to: 'users#create'
	
	post '/search_student', to: 'students#search'
	

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/searchindiv', to: 'viewindiv#new'
  post '/searchindiv', to: 'viewindiv#search'

  post '/student_pdf', to: 'students#save'
  post '/personnel_pdf', to: 'personnels#save'
end

app/models/teach.rb
class Teach < ApplicationRecord
  belongs_to :section
  belongs_to :personnel
end

app/controllers/teaches_controller.rb
class TeachesController < ApplicationController
  before_action :set_teach, only: [:show, :edit, :update, :destroy]

  # GET /teaches
  # GET /teaches.json
  def index
    @teaches = Teach.all
		respond_to do |format|
			format.html { render :index }
			format.json { render json: Oj.dump(@teaches) }
		end

  end

  # GET /teaches/1
  # GET /teaches/1.json
  def show
		respond_to do |format|
      format.html { render :show }
      format.json { render json: Oj.dump(@teaches) }
    end

  end

  # GET /teaches/new
  def new
    @teach = Teach.new
  end

  # GET /teaches/1/edit
  def edit
  end

  # POST /teaches
  # POST /teaches.json
  def create
    @teach = Teach.new(teach_params)

    respond_to do |format|
      if @teach.save
        format.html { redirect_to @teach, notice: 'Teach was successfully created.' }
        format.json { render :show, status: :created, location: @teach }
      else
        format.html { render :new }
        format.json { render json: @teach.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teaches/1
  # PATCH/PUT /teaches/1.json
  def update
    respond_to do |format|
      if @teach.update(teach_params)
        format.html { redirect_to @teach, notice: 'Teach was successfully updated.' }
        format.json { render :show, status: :ok, location: @teach }
      else
        format.html { render :edit }
        format.json { render json: @teach.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teaches/1
  # DELETE /teaches/1.json
  def destroy
    @teach.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Teach was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teach
      @teach = Teach.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teach_params
      params.fetch(:teach, {})
    end
end

app/helpers/teaches_helper.rb
module TeachesHelper
end

app/views/teaches/_form.html.erb
<%= form_for(teach) do |f| %>
  <% if teach.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(teach.errors.count, "error") %> prohibited this teach from being saved:</h2>

      <ul>
      <% teach.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teaches/edit.html.erb
<h1>Editing Teach</h1>

<%= render 'form', teach: @teach %>

<%= link_to 'Show', @teach %> |
<%= link_to 'Back', teaches_path %>

app/views/teaches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Teaches</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teaches.each do |teach| %>
      <tr>
        <td><%= link_to 'Show', teach %></td>
        <td><%= link_to 'Edit', edit_teach_path(teach) %></td>
        <td><%= link_to 'Destroy', teach, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teach', new_teach_path %>

app/views/teaches/new.html.erb
<h1>New Teach</h1>

<%= render 'form', teach: @teach %>

<%= link_to 'Back', teaches_path %>

app/views/teaches/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_teach_path(@teach) %> |
<%= link_to 'Back', teaches_path %>