config/routes.rb
Rails.application.routes.draw do
  resources :teaches
  resources :events
  resources :participates
  resources :competes
  resources :codes
  resources :course_categories
  resources :belong_tos
  resources :groups
  resources :advisors
  resources :log_breaks
  resources :rules
  resources :personal_leaves
  resources :sick_leaves
  resources :leaves
  resources :competitions
  resources :activities
  resources :portfolios
  resources :gpas
  resources :students
  resources :schedules
  resources :time_slots
  resources :enrollments
  resources :sections
  resources :requires
  resources :courses
  resources :curriculums
  resources :departments
  resources :personnels

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'static_pages#index'

  get 'sessions/new'
  post '/signup', to: 'users#create'
	
	post '/search_student', to: 'students#search'
	

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/searchindiv', to: 'viewindiv#new'
  post '/searchindiv', to: 'viewindiv#search'

  post '/student_pdf', to: 'students#save'
  post '/personnel_pdf', to: 'personnels#save'
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
	belongs_to :section
	belongs_to :student
	
	def getGrade
		if (!grade)
			return ''
		elsif (grade.floor == 0)
			return 'F'
		else
			return (69-grade.floor.to_i).chr.to_s + ((grade.floor!=grade) ? "+" : "")
		end
	end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_personnel

  # GET /enrollments
  # GET /enrollments.json
  def index
    @enrollments = Enrollment.all
    respond_to do |format|
			format.html { render :index }
			format.json { render json: Oj.dump(@enrollments) }
		end
  end

  # GET /enrollments/1
  # GET /enrollments/1.json
  def show
    respond_to do |format|
      format.html { render :show }
      format.json { render json: Oj.dump(@enrollment) }
    end
  end

  # GET /enrollments/new
  def new
    @enrollment = Enrollment.new
  end

  # GET /enrollments/1/edit
  def edit
  end

  # POST /enrollments
  # POST /enrollments.json
  def create
    @enrollment = Enrollment.new(enrollment_params)


		if(!@enrollment.grade)
			@enrollment.grade = nil
		#else
		#	@grade = 0
		#	if (@enrollment.grade.length==2)
		#		@grade = 0.5;
		#	end
		#
		#	if (@enrollment.grade != "F")
		#		@enrollment.grade = @enrollment.grade[0].ord - "D".ord
		#	end
		#	@enrollment.grade += @grade;
		end

    if(Enrollment.where(section_id: @enrollment.section_id).where(student_id: @enrollment.student_id).count() > 0)
      redirect_to :back, notice: "duplicate enrollments"
    else
  		respond_to do |format|
        if @enrollment.save
          format.html { redirect_to :back, notice: 'Enrollment was successfully created.' }
          format.json { render :show, status: :created, location: @enrollment }
        else
          format.html { redirect_to :back, notice: @enrollment.errors }
          format.json { render json: @enrollment.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /enrollments/1
  # PATCH/PUT /enrollments/1.json
  def update

    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to @enrollment.section, notice: 'Enrollment was successfully updated.' }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollments/1
  # DELETE /enrollments/1.json
  def destroy

    @enrollment.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Enrollment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enrollment
      @enrollment = Enrollment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enrollment_params
      params.fetch(:enrollment, {}).permit(:student_id, :grade, :section_id)
    end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_form.html.erb
<div class="row">
  <div class="input-field col s6">
    <input id="code"  type="text" class="validate" value="<%= enrollment.section.course.name %>" disabled>
    <label for="code" class="active">Course</label>
  </div>
  <div class="input-field col s6">
    <input id="name" type="text" class="validate" value="<%= enrollment.section.sec %>" disabled>
    <label for="name" class="active">Section</label>
  </div>
</div>

<div class="row">
  <div class="input-field col s6">
    <input id="name" type="text" class="validate" value="<%= enrollment.student.id %>" disabled>
    <label for="name" class="active">Student</label>
  </div>
  <div class="input-field col s6">
    <input id="credit" name="enrollment[grade]" type="text" class="validate" required value="<%= enrollment.grade %>" placeholder="0, 0.5, 2, 4">
    <label for="credit" class="active">Grade</label>
  </div>
</div>

app/views/enrollments/_list.html.erb
<table id="list" class="bordered highlight" cellspacing="0" width="100%">
	<thead>
			<tr>
					<th>Code</th>
					<th>Name</th>
					<th></th>
			</tr>
	</thead>
</table>


<script>
  $(function() {
		if ($('#list_wrapper').length == 0) {
      $('#list').DataTable({
				"pageLength": 15,
				"bLengthChange": false,
        "ajax": {
					"url": "/departments.json",
					"dataSrc": ""
        },
        "deferRender": true,
				"columns": [
						{ "data": "id" },
						{ "data": "name" },
						{
							"orderable": false,
							"render": function(data, type, row) {
								return "<a href='/departments/" + row.id + "'><i class='material-icons'>description</i></a>&nbsp;&nbsp;&nbsp;"+
                 			 "<a href='/departments/" + row.id + "/edit'><i class='material-icons'>build</i></a>&nbsp;&nbsp;&nbsp;"+
                			 "<a data-confirm='You sure?' rel='nofollow' data-method='delete' href='/departments/" + row.id + "'><i class='material-icons'>delete</i></a>";
							}
						}
        ]
			});
		}
  });
</script>

app/views/enrollments/_modalNew.html.erb
<div id="modal-add" class="modal modal-fixed-footer modal-fixed-header">
  <%= form_for(:department) do |f| %>
    <div class="modal-header">
      <h5>Add department</h5>
    </div>
    <div class="modal-content">
      <%= render 'form', department: Department.new %>
    </div>
    <div class="modal-footer">
      <button type="submit" class="waves-effect waves-green btn-flat">Add</button>
      <a class="modal-action modal-close waves-effect waves-red btn-flat">Cancel</a>
    </div>
  <% end %>
</div>

<div class="fixed-action-btn horizontal">
  <a data-target="modal-add" class="btn btn-floating btn-large waves-effect waves-light red">
    <i class="material-icons">add</i>
  </a>
</div>

app/views/enrollments/edit.html.erb
<% provide(:title, "Edit enrollment") %>
<h5>Update enrollment</h5>
<hr><br>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@enrollment) do |f| %>
      <%= render 'form', enrollment: @enrollment %>
      <button type="submit" class="waves-effect waves-green btn" style="float:right;">Update</button>
    <% end %>
  </div>
</div>

<%= link_to 'Back', @enrollment.section %>

app/views/enrollments/index.html.erb
<h1>Enrollments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enrollments.each do |enrollment| %>
      <tr>
        <td><%= link_to 'Show', enrollment %></td>
        <td><%= link_to 'Edit', edit_enrollment_path(enrollment) %></td>
        <td><%= link_to 'Destroy', enrollment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Enrollment', new_enrollment_path %>

app/views/enrollments/new.html.erb
<h1>New Enrollment</h1>

<%= render 'form', enrollment: @enrollment %>

<%= link_to 'Back', enrollments_path %>

app/views/enrollments/show.html.erb
<%= link_to 'Edit', edit_enrollment_path(@enrollment) %> |
<%= link_to 'Back', enrollments_path %>