config/routes.rb
Rails.application.routes.draw do
  resources :teaches
  resources :events
  resources :participates
  resources :competes
  resources :codes
  resources :course_categories
  resources :belong_tos
  resources :groups
  resources :advisors
  resources :log_breaks
  resources :rules
  resources :personal_leaves
  resources :sick_leaves
  resources :leaves
  resources :competitions
  resources :activities
  resources :portfolios
  resources :gpas
  resources :students
  resources :schedules
  resources :time_slots
  resources :enrollments
  resources :sections
  resources :requires
  resources :courses
  resources :curriculums
  resources :departments
  resources :personnels

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'static_pages#index'

  get 'sessions/new'
  post '/signup', to: 'users#create'
	
	post '/search_student', to: 'students#search'
	

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/searchindiv', to: 'viewindiv#new'
  post '/searchindiv', to: 'viewindiv#search'

  post '/student_pdf', to: 'students#save'
  post '/personnel_pdf', to: 'personnels#save'
end

app/models/advisor.rb
class Advisor < ApplicationRecord
	belongs_to :student
	belongs_to :personnel
end

app/controllers/advisors_controller.rb
class AdvisorsController < ApplicationController
  before_action :set_advisor, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_personnel

  # GET /advisors
  # GET /advisors.json
  def index
    @advisors = Advisor.all
    respond_to do |format|
			format.html { render :index }
			format.json { render json: Oj.dump(@advisors) }
		end
  end

  # GET /advisors/1
  # GET /advisors/1.json
  def show
    respond_to do |format|
      format.html { render :show }
      format.json { render json: Oj.dump(@advisor) }
    end
  end

  # GET /advisors/new
  def new
    @advisor = Advisor.new
  end

  # GET /advisors/1/edit
  def edit
  end

  # POST /advisors
  # POST /advisors.json
  def create
    @advisor = Advisor.new(advisor_params)

    respond_to do |format|
      if @advisor.save
        format.html { redirect_to @advisor, notice: 'Advisor was successfully created.' }
        format.json { render :show, status: :created, location: @advisor }
      else
        format.html { render :new }
        format.json { render json: @advisor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /advisors/1
  # PATCH/PUT /advisors/1.json
  def update
    respond_to do |format|
      if @advisor.update(advisor_params)
        format.html { redirect_to @advisor, notice: 'Advisor was successfully updated.' }
        format.json { render :show, status: :ok, location: @advisor }
      else
        format.html { render :edit }
        format.json { render json: @advisor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /advisors/1
  # DELETE /advisors/1.json
  def destroy

    @advisor.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Advisor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_advisor
      @advisor = Advisor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def advisor_params
      params.fetch(:advisor, {})
    end
end

app/helpers/advisors_helper.rb
module AdvisorsHelper
end

app/views/advisors/_form.html.erb
<%= form_for(advisor) do |f| %>
  <% if advisor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(advisor.errors.count, "error") %> prohibited this advisor from being saved:</h2>

      <ul>
      <% advisor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/advisors/edit.html.erb
<h1>Editing Advisor</h1>

<%= render 'form', advisor: @advisor %>

<%= link_to 'Show', @advisor %> |
<%= link_to 'Back', advisors_path %>

app/views/advisors/index.html.erb
<h1>Advisors</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @advisors.each do |advisor| %>
      <tr>
        <td><%= link_to 'Show', advisor %></td>
        <td><%= link_to 'Edit', edit_advisor_path(advisor) %></td>
        <td><%= link_to 'Destroy', advisor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Advisor', new_advisor_path %>

app/views/advisors/new.html.erb
<h1>New Advisor</h1>

<%= render 'form', advisor: @advisor %>

<%= link_to 'Back', advisors_path %>

app/views/advisors/show.html.erb
<%= link_to 'Edit', edit_advisor_path(@advisor) %> |
<%= link_to 'Back', advisors_path %>